// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFfk82dTErYPSFtT6ckDTqbZxGnCyB2HU',
    appId: '1:1041348416909:web:f9c473a61f89519615d9c4',
    messagingSenderId: '1041348416909',
    projectId: 'chattr-43009',
    authDomain: 'chattr-43009.firebaseapp.com',
    storageBucket: 'chattr-43009.appspot.com',
    measurementId: 'G-1VC8YJY90B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTkfwHEDu6ep-hJ2RDdSNXrP1uUtSGOWc',
    appId: '1:1041348416909:android:4ab0e88db407035e15d9c4',
    messagingSenderId: '1041348416909',
    projectId: 'chattr-43009',
    storageBucket: 'chattr-43009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpv-8p8hDKROwCwHk9fnU3aSmnasKJy0',
    appId: '1:1041348416909:ios:88ebd60346fd3d9915d9c4',
    messagingSenderId: '1041348416909',
    projectId: 'chattr-43009',
    storageBucket: 'chattr-43009.appspot.com',
    iosClientId: '1041348416909-hv32ntoqqtiluncb10jcmuj9pallrt28.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattr',
  );
}
